app:
  name: Scraper
  version: 0.1

server:
  host: localhost
  port: 8088

urls:
  table_url: 'https://proglib.io/p/slozhnost-algoritmov-i-operaciy-na-primere-python-2020-11-03'

postgres:
  connection: 'postgresql+psycopg2://postgres:2@localhost:5432/postgres2'

data_types:
  - list
  - set
  - dict
